name: Build and Push Image
on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   types:
  #     - labeled
  #     - opened
  #     - edited
  #     - reopened
  #     - synchronize
  #   branches:
  #     - main

  # have the ability to trigger this workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ansible-chatbot-service
        containerfiles: |
          ./Containerfile
